### ISSUE TITLE
502 when hosting a managed WebApi site in IIS as a sub-app under a unmanaged site running on kestrel

### ISSUE THREAD

**Issue by Tratcher** [aspnet/IISIntegration#113]
_From @larswise on April 2, 2016 12:6_

When hosting a asp.net mvc 6 site in iis, running kestrel, with a sub app below running in managed mode the sub app fails with a 502 - Web server received an invalid response while acting as a gateway or proxy server. 

Structure:
Default Web site -> (SubApp) ASPNETMVC6/Kestrel, Unmanaged -> (SubSubApp) WebApi .NET 4.6 Managed

Don't know if this is by design but this setup works when all app-pools are managed.
I moved the WebApi alongside with the ASP.NET MVC6 site like this

Default Web site -> ASPNETMVC6/Kestrel, Unmanaged
Default Web site -> WebApi .NET 4.6 Managed

And it worked.
Not sure why this happened but I would suspect kestrel?

IIS 8
Microsoft.AspNet.Server.Kestrel 1.0.0-rc1-final
Windows Server 2012 R2

_Copied from original issue: aspnet/KestrelHttpServer#724_

**Comment by Tratcher** [comment]
_From @larswise on April 2, 2016 12:25_

```
<system.webServer>
    <handlers>
      <remove name="httpPlatformHandler"/>
```
on the webapi site did not seem to solve it.

**Comment by muratg** [comment]
Let's investigate post RC2.

**Comment by dml5** [comment]
When will that be?  Not being able to create a sub site under a MVC6 site has been an issue for months.  None of the solutions I have tried work.

**Comment by pan-wang** [comment]
I could not repro this issue with AspNetCore Module. Here is my app structure: DefaultWebSite ->AspNetCore App (subApp)-->WebApi App (subsubApp).  AspNetCore App uses apppool 'aspnetcore' which is set to no managed code; WebApi App uses apppool 'webapi' which is set to .Net Clr v4.0. In the web.config of WeebApi App, I did add the following  changes as suggested by @Tratcher 
_<system.webServer>
    <handlers>
      <remove name="aspNetCore" />
Note without this handlers removal, I did hit 502 error.  If you can still repro this issue after updating the web.config, could you please share your app and IIS applicationhost.config so that I can take a look.

**Comment by Tratcher** [comment]
Full config for AspNetCoreModule:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <remove name="aspNetCore"/>
    </handlers>
  </system.webServer>
</configuration>
```

Or httpPlatform for HttpPlatformHandler:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <remove name="httpPlatform"/>
    </handlers>
  </system.webServer>
</configuration>
```
