### ISSUE TITLE
Aspnetcore Module and .NET Core versions support

### ISSUE THREAD

**Issue by ehouarn-perret** [aspnet/IISIntegration#1138]
Hi, is there a list of the .NET Core versions supported for each version of Aspnetcore Module?
Is it like 1:1?

**Comment by jkotalik** [comment]
The AspNetCoreModule (ANCM) is backwards compatible. This means that each version of the Windows Hosting Bundle will contain the same version of ANCM. All versions of dotnet should work with all versions of the AspNetCoreModule, however we recommend using the latest version due to MSRC/security issues that have been resolved in the latest version.

**Comment by ehouarn-perret** [comment]
@jkotalik thanks!
