### ISSUE TITLE
Move web.config to root

### ISSUE THREAD

**Issue by glennc** [aspnet/IISIntegration#115]
In order to make us more reliable on IIS we are going to move the web.config into the root of the published output instead of the web root.

@muratg

**Comment by muratg** [comment]
@Tratcher

**Comment by muratg** [comment]
@moozzyk

**Comment by Tratcher** [comment]
@BillHiebert FYI

**Comment by GuardRex** [comment]
A hair of guidance for RC2-nightly folks ...

1. Copy `web.config` from `wwwroot` to the app base.
2. Edit the file and change paths for `processPath` and `stdoutLogFile`. Simply remove a dot from each ... for example go from `processPath="..\my_app.exe"` to `processPath=".\my_app.exe"`. Save the file.
3. Stop the AppPool.
4. Re-point the Physical path in IIS to the app base in Basic Settings.
5. Restart the AppPool.
6. Delete `web.config` from the `wwwroot` directory.

... of course, mirror changes in app code. Done! Grab a :beer:.

**Comment by Tratcher** [comment]
@GuardRex what changes did you need to make in app code?

**Comment by GuardRex** [comment]
@Tratcher ... None ... there is some debate right now on JabbR whether or not I'm playing with a full deck of cards. The "he's not" group is in the majority! :smile:

When I said "app code," I only meant in the project ... I didn't mean actual "application code." Sorry. When you see the :beer: emoji, that means you should take me even less seriously than usual.

Good news is that these configuration changes went great this evening. All apps are smiling :smile: and working just fine.

**Comment by moozzyk** [comment]
Does this affect templates as well? I remember adding wwwroot to the content section in project.json just to make sure that web.config is copied. Now we should probably leave it to the user because by default we will not have anything to copy so we should not add wwwroot to the content section in project.json. /cc @rustd

Also the publish iis tool looks for the config file in the wwwroot folder and create one wwwroot folder if one does not exist. We also won't should no longer set the path to the application base.

**Comment by muratg** [comment]
Yes, this would impact templates. @JunTaoLuo should send a PR there once we have this ready.

**Comment by JunTaoLuo** [comment]
@davidfowl you have been nominated by @Tratcher to write the announcement for this change.
