### ISSUE TITLE
Discussion for: Changes to the publish-iis tool

### ISSUE THREAD

**Issue by moozzyk** [aspnet/IISIntegration#139]
Discussion for https://github.com/aspnet/Announcements/issues/169

**Comment by GuardRex** [comment]
> the tool needs now to distinguish portable apps from standalone apps to be able to write the web.config file correctly depending on the application type that is being published. This required adding a new, mandatory parameter --framework that tells the tool what framework the application was published for.

Could you clarify what you mean by "framework," in this context ... not the TFM, correct? Could you show one `project.json` that the tool will respect for a shared version of `web.config` and a `project.json` that will be respected for standalone `web.config` output?

I thought it was the presence of `"type": "platform"` on the `Microsoft.NETCore.App` package that determined if an app will publish shared vs. standalone. If that's the case, then why doesn't the tool look for that specification on the package rather than require a `--framework` switch? [Perhaps with the presence of an RID on the `dotnet publish` command or the RID of the `runtimes` if there is only one listed, since shared framework apps probably/likely won't have a `runtimes` section.]

**Comment by moozzyk** [comment]
The thing to pass as the `--framework` is the full target framework name (e.g. .NETCoreApp,Version=v1.0). In reality you almost never will have to pass anything manually since you will run the tool as a postpublish script and it will use the parameters passed by the publish command. You can see it here:

```
  "scripts": {
    "postpublish": "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%"
  },
```

This is true that whether the application is portable or stand alone is decided based on the existence of `"type":  "platform"` in the project.json but as any dependency it can be either general or framework specific. Currently you can build an app using either netcoreapp1.0 or netstandardapp1.5 monikers. Granted, netstandardapp1.5 is going away but if you are suggesting the I should hardcode netcoreapp1.0 then I don't think it is a good idea. `1.0` in netcoreapp tells me that there can be `1.1` in the future and can have different requirements or behavior. And there there is also `net451`+ which is always an .exe.

**Comment by LeandroPT** [comment]
The postpublish script works fine and we.config is generated.

However i am hitting #137

**Comment by GuardRex** [comment]
> if you are suggesting the I should hardcode netcoreapp1.0 then I don't think it is a good idea. 

No, I was just confused and not taking into account the post-publish nature of the way it runs (apparently `"postpublish"` wasn't clear enough to me :smile: orf!). It makes sense now. Thanks for the clarification.

**Comment by LeandroPT** [comment]
Working just fine.

However, i find the output structure weird...

Why has the approot / www structure been abandoned?

**Comment by mikes-gh** [comment]
@LeandroPT 
I believe approot has been abandoned.
Everything that was in approot is moved down one  level.
wwwroot still exists as a sub folder at the new level..
Rather than pointing your IIS web application to the approot you will need to point it to the new level (one down).
web.config has also moved down to allow for this
That's how its working for me.

**Comment by LeandroPT** [comment]
I did all sort of experiences... Works anyway you want... that is the beauty of this thing

**Comment by mikes-gh** [comment]
Latest tooling template shown on aspnet community standup missing --framework in project.json
``` 
"scripts": {
    "postpublish": "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%"
  },
```
When I didnt have the --framework option it didnt work for me

**Comment by moozzyk** [comment]
@mikes-gh - these changes went in last Friday - so after the standup.

**Comment by mikes-gh** [comment]
I believe standup was live today. Scott using latest tooling drop just out.
Template here note no framework switch
https://github.com/aspnet/Templates/blob/dev/src/BaseTemplates/StarterWeb/project.json

**Comment by moozzyk** [comment]
Changes to templates were merged only today so they probably were not in the build they showed. (And looks like I missed the standup...)

**Comment by GuardRex** [comment]
I opened a feature request as a separate issue b/c I'm hoping that it gets some :heart: and could at least land on the backlog: https://github.com/aspnet/IISIntegration/issues/144

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
