### ISSUE TITLE
asp.net - DotNet Core 2.1.5 Hosting Setup Failed

### ISSUE THREAD

**Issue by nk111** [aspnet/IISIntegration#1563]
I'm trying to install "dotnet-hosting-2.1.5-win" on a server 2012 R2. The setup fails with the attached log.
[dd_dd_DotNetCoreWinSvrHosting__20181026082036.log](https://github.com/aspnet/IISIntegration/files/2518400/dd_dd_DotNetCoreWinSvrHosting__20181026082036.log)

![image](https://user-images.githubusercontent.com/155322/47555126-49c03100-d90b-11e8-8ae7-9a1fc8b2052c.png)

There are no separate logs for the failing msi packages. 

Any advice?

**Comment by nk111** [comment]
> If you go to your %Temp% folder, there should be more logs created with similar names. Can you check for a log file name that ends with AspNetCoreModule and paste output here?

Sorry but:
"There are no separate logs for the failing msi packages."

really not!

**Comment by nk111** [comment]
Looks like i have to apologize... I just reconnected to the server and this time i found the additional logs. I swear there wasn't any to be seen as long as i was connected yesterday.

However...
The log showed me this:
`MSI (s) (AC:CC) [10:38:09:413]: Created Custom Action Server with PID 8328 (0x2088).
MSI (s) (AC:A8) [10:38:09:444]: Running as a service.
MSI (s) (AC:A8) [10:38:09:444]: Hello, I'm your 32bit Elevated Non-remapped custom action server.
CAQuietExec:  Unlocked section "system.webServer/handlers" at configuration path "MACHINE/WEBROOT/APPHOST".
CAQuietExec:  ERROR ( hresult:80070005, message:Failed to commit configuration changes.  
CAQuietExec:  
Access is denied.
CAQuietExec:  
 )
CAQuietExec:  Error 0x80070005: Command line returned an error.
CAQuietExec:  Error 0x80070005: QuietExec Failed
CAQuietExec:  Error 0x80070005: Failed in ExecCommon method`

And this made me remember that we usually keep our applicationHost.config under

"C:\Windows\System32\inetsrv\config\applicationHost.config"

write protected. Removed the write protection and installation succeeded.

Thanks!

**Comment by Phlow2001** [comment]
A note for posterity.  I did locate the AspNetCoreModule log, and determined it was also an Access Denied error.  However, mine was due to being a shared configuration applicationHost.config on network drive.

I found another post from 2016 where it was pointed out that the installers can't handle shared configuration setups.  So the instructions were switch back to non-shared configuration and then install the msi.  Then you have to go through the manual steps of compare/copy the changes to the shared config, and run the msi for each server in your farm.

This is quite a pain.  The installer was unhelpful here, entirely.  Perhaps redirection.config could have been checked for a configurationRedirection enabled="true" and if access is denied, give some kind of helpful information on what is needed in the shared configuration environment?  Some documentation somewhere for how to run get up and running in a web farm?

**Comment by jkotalik** [comment]
>  Perhaps redirection.config could have been checked for a configurationRedirection enabled="true" and if access is denied, let the user know to check the docs. 

This seems like a plausible option. @joeloff thoughts?

**Comment by joeloff** [comment]
@jkotalik Is the idea to just skip installing a component from ANCM if that attribute is set?

**Comment by joeloff** [comment]
@nk111 I looked at the original bundle log you attached. It shows that the expected log file would have been under the AppData folder of the user that ran the install;

C:\Users\user~1\AppData\Local\Temp\dd_dd_DotNetCoreWinSvrHosting__20181026082036_000_AspNetCoreModule_x64.log

**Comment by jkotalik** [comment]
@joeloff the TL;DR of the situation is when the hosting bundle runs, ANCM tries to update the applicationhost.config file in inetsrv. However, this applicationhost.config file can be redirected to another location by specifying another path in a file called redirection.config. If this attribute is enabled today, the installers will fail. 

This scenario is fairly common. I think the lowest friction thing to change would be to make the hosting bundle point to the docs site https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.1#install-the-net-core-hosting-bundle.
