### ISSUE TITLE
Question: what is the correct framework to use for aspnetcore web applications to host them correctly in IIS? 

### ISSUE THREAD

**Issue by Challagolla** [aspnet/IISIntegration#168]
Hi Team,

Could someone educate me on what are the framework that a web application built using latest aspnet core rc2 packages should use to host it correctly in IIS?  does IIS supports running the net451 version?  or do we need to port to netcoreapp1.0 ?  can we find some documentation anywhere regarding the usage of the target frameworks that we need to use to host the applicaitons correctly ? 

Thanks in Advance

**Comment by GuardRex** [comment]
@Challagolla Docs are on the way and a WIP right now. This week is a particularly transitional period, as they are trying to put out RC2 release by "mid-May." There are a multitude of doc updates that will hit when RC2 releases, because there were so many updates for RC2. Here are some links that may be of help: https://github.com/dotnet/cli/issues/2135#issuecomment-212692267. You'll want to pay particular attention to the cli-samples and the IISIntegration samples for IIS.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
