### ISSUE TITLE
dotnet publish-iis keeps adding the app name to web.config

### ISSUE THREAD

**Issue by CIPop** [aspnet/IISIntegration#221]
Following https://docs.asp.net/en/latest/publishing/iis.html:

I'm using the Getting started project and have the following `project.json`:

```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true
  },
  "dependencies": {},
  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0"
        },
        "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
        "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0"
      },
      "imports": "dnxcore50"
    }
  },
  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-*"
  },
  "scripts": {
    "postpublish": "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%"
  }
}
```

If I call the following four times:
`dotnet publish`

The web.config will have the following line (note that the app name keeps getting added):

`<aspNetCore processPath="dotnet" arguments=".\aspnetcoreapp.dll .\aspnetcoreapp.dll .\aspnetcoreapp.dll .\aspnetcoreapp.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
`

Also, I have a web.config in my app but it's being ignored (that one has stdoutLogEnabled="true").

**Comment by GuardRex** [comment]
Try
```
"Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
```

**Comment by moozzyk** [comment]
publish-iis tries to preserve arguments and is replacing only %LAUNCHER_ARGS%. So, if your web.config is already set up correctly you probably should disable publish-iis in the postpublish script.

One thing that I am a bit surprised is that you have many `.\aspnetcore.dll`. publish-iis works only on the web.config file that was already published so I would expect at most one extraneous `.\aspnetcore.dll`. Since you have many it looks like they are being changed in the source web.config file - are you publishing to the folder where the source lives thus overwriting the source web.config each time?

**Comment by dkent600** [comment]
Same thing is happening to me.  I _don't_ have a web.config in my project --  `publish-iis` is generating the web.config on its own.  But each time I run `publish-iis` it adds another instance of the name of the dll to the `arguments` attribute of `aspNetCore`.

**Comment by moozzyk** [comment]
I don't think it is possible for publish-iis to append anything if there is no web.config file since it is writing the config from scratch. Please note that publish-iis reads config from the publish folder and not the application folder so even if you did not have web.config in your application and you publish to a target folder it will create one. If you publish again to the same folder, because you did not have a web.config in your app, the one created during the first publish was not overwritten by anything and therefore it is the one that publish-iis uses which results in appending to the path. One of the workarounds would be to delete the web.config file from the publish destination folder before publishing.

**Comment by dkent600** [comment]
@moozzyk Indeed it happens when you publish more than once in a row.  Yes, deleting would be the work-around.  I was hoping that `publish-iis` would have an option to delete everything in the destination before publishing, but haven't been able to find it.  (Haven't in fact been able to find *any* docs on the command-line arguments for that command.)

**Comment by GuardRex** [comment]
@dkent600 I probably could have (or *should have*) provided some more detail here: https://docs.microsoft.com/en-us/aspnet/core/publishing/iis#publish-iis-tool

... and I would do so, except that the `publish-iis` tool is going away with the move to MSBuild/csproj. Soon, that section is going to change over to address how `Microsoft.NET.Sdk.Web` handles `web.config`.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
