### ISSUE TITLE
Update application files without stopping IIS

### ISSUE THREAD

**Issue by muratg** [aspnet/IISIntegration#238]
_From @mojtabakaviani on July 14, 2016 10:32_

Now, when I want update application file on IIS server. show error that the action can't be completed because the folder or a file in it is open in another program. and must stop IIS and copy/paste file and then start IIS.

_Copied from original issue: aspnet/KestrelHttpServer#970_

**Comment by muratg** [comment]
_From @moozzyk on July 14, 2016 17:31_

AspNetCoreModule supports app offline feature. You drop the app_offline.htm file which will make IIS stop your application (and serve the contents of the app_offline.htm file) then you can update your app. Once you are done you remove the app_offline.htm file. WebDeploy does this for you when you publish to Azure. I think it does not do this when publishing to file system but @vijayrkn knows how to configure this.

**Comment by muratg** [comment]
_From @vijayrkn on July 14, 2016 17:43_

If you are using a "filesystem" profile to publish (which has `<WebPublishMethod>FileSystem</WebPublishMethod>`), then you need to add 
`<EnableMSDeployAppOffline>True</EnableMSDeployAppOffline>` to support app_offline. While publishing to Azure, this property is automatically added to your pubxml.

**Comment by muratg** [comment]
_From @GuardRex on July 14, 2016 17:51_

Cross ref issues ...
https://github.com/aspnet/IISIntegration/issues/226
https://github.com/aspnet/Home/issues/694

**Comment by geeeyetee** [comment]
Another cross ref issue (see comments regarding on-premises products being similarly affected):
https://github.com/Microsoft/vsts-tasks/issues/1607

**Comment by muratg** [comment]
@vijayrkn any ideas on the above?

**Comment by vijayrkn** [comment]
Could be related to this bug - https://github.com/aspnet/Home/issues/694#issuecomment-270175753. 

A recent change in ANCM made app_offline case sensitive.

**Comment by rnagpal** [comment]
@vijayrkn I was hoping that setting EnableMSDeployAppOffline as True in my .pubxml should take care of that. Can you point me to specific instructions on how to achieve this using app_offline.htm?

**Comment by vijayrkn** [comment]
When this property is set EnableMSDeployAppOffline' msdeploy drops App_Offline.htm during publish time and removes it after publish. Ideally ASP.NET Core module should take care of bringing the site down when this file is dropped. 

In the latest release of ANCM(ASP.NET core module), it looks for a case-sensitive app_offline.htm. Because of this, setting EnableMSDeployAppOffline wont bring down the site (because msdeply drops App_Offline.htm).

**Comment by shahjay748** [comment]
When my .net core web application is running and I am trying to publish a new build, it gives me error that DLLs are in use. So I have to Stop the app pool, then update the DLLs and start the App Pool.

Is there any workaround in .Net Core by which I can publish the new Build/DLLs without stopping the App Pool ?

This is by default supported in .Net framework using shadow copy mechanism. Unfortunately, It's been 2 years since the launch of .Net core and seems like there's still no support for such very basic and required functionality. Is there even any plans to fix this in future ?

Thanks in advance for any help.

**Comment by haifengwang** [comment]
This issue has been closed and there seems to be no solution. 😭

**Comment by RolandoAvila** [comment]
Hi Vijay,

I am getting the following error:

Error MSB3061: Unable to delete file

It appears the dotnet.exe has a handle to it as other’s have stated. However, when I end the process I can delete the files. But as soon as I publish from VS2017 it is bringing my server down. This is new. I don’t know if this is a coincidence with something else happening on the network but this has been reproducible.

I used to deploy by stopping the application on the server, which allowed did the job but not consistently. In some cases I would have to click on the publish button about 20 times consecutively.

I will work with my network folks to see if they can monitor what’s going on, but this was never a problem with non-.netcore apps.

Rolando

**Comment by vijayrkn** [comment]
If you are publishing to an IIS server, have you tried using the MSDeploy profile instead of FileSystem? If it is an MSDeploy profile, you can set the following property in the pubxml (under Properties\Publish Profiles)

`<EnableAppOffline>true</EnableAppOffline>`

This will take care of bringing the site down before publishing. You should not run into issues with deleting files with this profile.

Publishing to a folder does not know if it is getting published to a live site or just a folder on the machine. Hence, it does not handle stopping the site before publishing. MSDeploy profiles are specifically meant to handle these scenarios (publishing to IIS etc). 

I dont quite understand what you mean by this. 

>But as soon as I publish from VS2017 it is bringing my server down.

If you are using folder publish and your application is down, then publishing should succeed. Would it be possible to share the logs (with the error) after removing sensitive content (if any) ? This will help us trouble shoot this issue faster.

**Comment by RolandoAvila** [comment]
I have not tried an MSDeploy yet. I have just spoken with my network folks here and we are going to set up some logs to see what is going on. They suspect it might be due to some recent changes to our firewall that could be contributing to this.

I found that the server is not going down, but I am losing connection to it, which is why we think it might be a firewall issue. I will let you know more once I find out.

I apologize for the inconvenience but appreciate your quick response. If I do find out what the root cause is I will update my comments accordingly.
