### ISSUE TITLE
subprotocol is not returned in WebSocket Upgrade / Accept Response

### ISSUE THREAD

**Issue by Tratcher** [aspnet/IISIntegration#240]
_From @rposener on April 27, 2016 20:51_

the following JS:
 `var exampleSocket = new WebSocket("ws://" + window.location.host, "test");` 
 when accepted by:
 `WebSocket webSocket = await httpContext.WebSockets.AcceptWebSocketAsync("test");` 
 does not include the header value:
 `Sec-WebSocket-Protocol:test`  

even though it should per spec.

_Copied from original issue: aspnet/WebSockets#79_

**Comment by Tratcher** [comment]
_From @muratg on April 28, 2016 16:40_

Tentatively putting this in 1.0.0. We'll investigate after RC2 ships.

**Comment by Tratcher** [comment]
_From @tmds on April 28, 2016 16:50_

@rposener what server are you using?

**Comment by Tratcher** [comment]
_From @rposener on April 28, 2016 17:1_

As best I understand it's kestral hosted within IISExpress (project is targeting dnx451 and dnxcore50) currently for rc1-update2

**Comment by Tratcher** [comment]
_From @tmds on April 28, 2016 17:59_

What should happen:
the value you give in AcceptWebSocketAsync should be set in the WebSocketAccept context [here](https://github.com/aspnet/HttpAbstractions/blob/3a97a6bdfdcc3787bf4b68cecdf277588de5ee76/src/Microsoft.AspNetCore.Http/Internal/DefaultWebSocketManager.cs#L60).
Then read from the context [here](https://github.com/aspnet/WebSockets/blob/0f9e4eba024078d2b0b2f1efb70a594b9ee70d0c/src/Microsoft.AspNetCore.WebSockets.Server/WebSocketMiddleware.cs#L97), passed on to [GenerateResponseHeaders](https://github.com/aspnet/WebSockets/blob/0f9e4eba024078d2b0b2f1efb70a594b9ee70d0c/src/Microsoft.AspNetCore.WebSockets.Server/WebSocketMiddleware.cs#L117) to end up in the header IEnumerable [here](https://github.com/aspnet/WebSockets/blob/0f9e4eba024078d2b0b2f1efb70a594b9ee70d0c/src/Microsoft.AspNetCore.WebSockets.Protocol/HandshakeHelpers.cs#L79), which then becomes part of the response headers [here](https://github.com/aspnet/WebSockets/blob/0f9e4eba024078d2b0b2f1efb70a594b9ee70d0c/src/Microsoft.AspNetCore.WebSockets.Server/WebSocketMiddleware.cs#L120).

Stepping through [AcceptAsync](https://github.com/aspnet/WebSockets/blob/0f9e4eba024078d2b0b2f1efb70a594b9ee70d0c/src/Microsoft.AspNetCore.WebSockets.Server/WebSocketMiddleware.cs#L87) may give you an idea of what the issue is. If you check out [Microsoft.AspNetCore.WebSockets.Server](https://github.com/aspnet/WebSockets/tree/0f9e4eba024078d2b0b2f1efb70a594b9ee70d0c/src/Microsoft.AspNetCore.WebSockets.Server) and add it to your 'src' folder, you should be able to set a breakpoint in that method.

**Comment by Tratcher** [comment]
Does it work if you run Kestrel directly without IISExpress?

**Comment by Tratcher** [comment]
_From @rposener on April 29, 2016 21:22_

Yes, works fine once IISExpress is removed from the mix.  Is there a way to allow that to pass through?

**Comment by Tratcher** [comment]
We'll have to investigate. @pan-wang, can you take a look?

**Comment by Tratcher** [comment]
_From @muratg on July 25, 2016 22:4_

@anurse Does SignalR use subprotocol in websockets?

**Comment by pan-wang** [comment]
ANCM code assumes IIS websocket module will add this sub protocol and thus does not add it for perf optimization. It seems this assumption is wrong. Will fix it in next release.

**Comment by lukaszkrzywizna** [comment]
Is this issue was resolved? 
I've got the same problem when I want to send AcceptWebSocketAsync() with subprotocol parameter thus I can't make connection between JS websocket and server. It works fine without IISExpress. 
I'm using the last version of IISIntegration (1.1.0) and WebSockets.Server (0.1.0).

**Comment by Tratcher** [comment]
WebSockets.Server (0.1.0)? That's really outdated. Can you repro this with the current sample app?
https://github.com/aspnet/WebSockets/blob/dev/samples/EchoApp/Startup.cs

**Comment by pan-wang** [comment]
if my memory is correct, this was fixed . Have you try ANCM with ASP.NET Core v1.1 release?

________________________________

**Comment by lukaszkrzywizna** [comment]
@Tratcher I'm talking about AspNetCore.WebSockets.Server and the last version of nuget package is 0.1.0 (https://www.nuget.org/packages/Microsoft.AspNetCore.WebSockets.Server/). EchoApp sample is inappropriate because it uses overload of AcceptWebSocketAsync() without subprotocol parameter.  Connection succeed when I want to create websocket connection without any subprotocols. However when I create Websocket instance in JS:
`var webSocket = new WebSocket("ws://localhost:17097/ws", ["wamp.2.json", "wamp.2.msgpack"]);`
and server build response:
`AcceptWebSocketAsync("wamp.2.json")`
I'm getting in chrome error:
`WebSocket connection to 'ws://localhost:17097/ws' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received`

Fiddler shows that server returns only Sec-WebSocket-Accept `header:

```
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Server: Kestrel
Sec-WebSocket-Accept: Rn9puo9WkRyvU4eUaEbf4mc/K5c=
Connection: Upgrade
X-SourceFiles: =?UTF-8?B?QzpcVXNlcnNcbGtyenl3aXpuYVxEZXNrdG9wXGFjLXJlcG9cc2VydmVyXEFib3ZlQ2xvdWRcc3JjXEFib3ZlQ2xvdWQuV2ViQXBpXHdz?=
X-Powered-By: ASP.NET
Date: Mon, 06 Feb 2017 11:23:20 GMT
EndTime: 12:23:21.118
ReceivedBytes: 0
SentBytes: 0
```

@pan-wang  I'm using ANCM with default configuration (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/aspnet-core-module) with the latest version of IISIntegration package and ASP.NET Core v1.1 release.

**Comment by Tratcher** [comment]
AspNetCore.WebSockets.Server is obsolete, it was replaced by AspNetCore.WebSockets https://www.nuget.org/packages/Microsoft.AspNetCore.WebSockets/

I recommended the EchoApp because it has the latest dependencies. It should be easy enough to add a sub-protocol there for testing.

**Comment by lukaszkrzywizna** [comment]
Ok, I've changed package to Microsoft.AspNetCore.WebSockets v1.0.0 - still the same situation, but when I've installed VS 2017 RC everything started to work properly. I'm guessing that was caused by replacing IISExpress with new version included in VS 2017.
