### ISSUE TITLE
AspNetCoreModule install failed when shared config is enabled.

### ISSUE THREAD

**Issue by ahjephson** [aspnet/IISIntegration#249]
AspNetCoreModule install failed when shared config is enabled.

CAQuietExec: Unlocked section "system.webServer/handlers" at configuration path "MACHINE/WEBROOT/APPHOST".
CAQuietExec: ERROR ( hresult:80070005, message:Failed to commit configuration changes.

CAQuietExec:

Access is denied.
CAQuietExec:

)

**Comment by muratg** [comment]
@shirhatti @pan-wang Did you guys want to do this in 1.1?

**Comment by shirhatti** [comment]
@jhkimnew Can you investigate?

**Comment by jhkimnew** [comment]
This is by design.

ANCM setup uses the local system account of the machine and if the system account does not have the access permission to the share path which is used by the IIS shared configuration, it skip configuring ANCM settings to the applicationhost.config on the share path directory because it ran into the access denied error.

Generally, we don’t recommend to install any IIS oob project when the shared configuration is enabled because the setup does not handle the shared configuration environment.

However, there is work-around way. Users simply can configure the applicationhost.config manually and then place the aspnetcore.dll which is under either “%windir%\system32\inetsrv” or “%ProgramFiles%\IIS Express” to all the machines which participate in the IIS shared configuration.

The right way to handle this is to disable the shared configuration temporarily and run ANCM setup. Now users can export the updated applicationhost.config to the shared configuration and then enable the shared configuration back.

Thanks,
Jeong Hwan Kim

**Comment by ahjephson** [comment]
If it is by design then that is fine. The  installer is not providing adequate feedback to the user as to why the install failed.

**Comment by muratg** [comment]
@shirhatti @pan-wang @jhkimnew Is it possible to detect and provide better feedback while installing? Or should we just document this?

**Comment by jhkimnew** [comment]
I think we need to document this. I already asked Sourabh about that.
I’d like to inform that the ANCM setup program is supposed be called only when installing the .Net Core bundle packages, which means that it will run in silent mode and users won’t be able to see any error.

**Comment by shirhatti** [comment]
Created a bug on the docs repo to track this

**Comment by muratg** [comment]
Cool, thanks folks!
