### ISSUE TITLE
Installing .NET Core 1.0.1 Windows Server Hosting fails with error 0x80072f76

### ISSUE THREAD

**Issue by comburo** [aspnet/IISIntegration#272]
I'm installed the .NET Core 1.0.1 Windows Server Hosting on a VM, but it keeps failing with:
0x80072f76 - Unspecified error.

I've inlcuded the install log file.

[dd_DotNetCoreWinSvrHosting__20160928152049.txt](https://github.com/aspnet/IISIntegration/files/498142/dd_DotNetCoreWinSvrHosting__20160928152049.txt)

**Comment by GuardRex** [comment]
I think that's the VC++ redist. Try a manual install from https://www.microsoft.com/en-us/download/details.aspx?id=53840 and run the installer again.

**Comment by comburo** [comment]
Yes, that fixes it.
This was on a Windows Server 2012 R2 VM. Shouldn't the installer at least tell the user this is a required dependency and offer a link where to download it from?

**Comment by GuardRex** [comment]
@joeloff will prob be able to say. This comes up from time-to-time, mostly when the machine doesn't have an Internet connection. The installer was fetching the VC++ redist from the Internet, so that would go sideways with no connection.

I currently have this listed in the Publish to IIS doc's Common Errors section, but I don't have it in the ANCM doc at https://docs.asp.net/en/latest/hosting/aspnet-core-module.html ... at least not yet.

May I ask: Which docs did you consult, if any, before running the installer? That may give us a clue where a note on this would make the most sense (besides, as you pointed out, from the installer itself).

**Comment by joeloff** [comment]
The VC redist requirement is a 3rd level dependency that comes from the CLI installer. The ideal fix is that the CLI that ships with the server bundle should have an embedded copy of the vc redist. I'll raise this again.

**Comment by GuardRex** [comment]
@joeloff ... then I'll hold off on sweating a doc update anywhere. I'll keep an eye out for an issue where you're working on bundling it.

**Comment by comburo** [comment]
@GuardRex: The thing is, the VM does have a working internet connection. So if the installer wanted to download the VC++ redist, it should have been able to.

I got instructions on this package from https://docs.asp.net/en/latest/publishing/iis.html
That page also links to the page you mentioned and I viewed that as well.

I found the page through googling (https://www.google.nl/search?q=install+asp.net+core+iis&oq=install+asp.net+core+iis&aqs=chrome..69i57.3463j0j4&sourceid=chrome&ie=UTF-8)

**Comment by comburo** [comment]
Just noticed @joeloff comment. Which makes it kind of ironic, since I didn't even want to install the full Core framework, just the IIS handler. I'm creating a self-contained application, so I was looking for a download of just the ACNM. I did found how to do this, by providing a command-line parameter to the installer, but a separate download is much more easy to discover in my opinion.

**Comment by joeloff** [comment]
@GuardRex It won't be a change we'll make. It will have to come from the CLI owners, but I'll raise the issue with them again. The alternative is that we simply add it to the hosting bundle, which might be simpler.

**Comment by GuardRex** [comment]
@joeloff Ok, I'll keep an eye out either way so I'll know if I need to beef-up those two docs.

@comburo 

> the VM does have a working internet connection

Interesting. There is another failure scenario at play then.

Thanks for letting me know on the docs you visited. I have it in the Common Errors section but not in the ANCM doc, and the language of a failure may have changed since I wrote that bit.

I'm going to wait and see how @joeloff fares with getting it bundled before making a doc change. I think that would lick this once and for all.

> but a separate download is much more easy to discover in my opinion

I heard from them that at some point that they were going to make the ANCM-only install a better experience than a command-line parameter ... checkbox or something. That was mentioned a while ago tho ... I think @DamianEdwards mentioned it in a Community Standup a couple of months ago.

**Comment by Tratcher** [comment]
There was an issue recently with the redist download link embedded in the .NET Core 1.0.1 installer. I'm told they're rebuilding the installer. https://github.com/dotnet/cli/issues/4190

**Comment by joeloff** [comment]
The CLI was rebuilt and we're rebuilding the server hosting bundle. The CLI installer was using an FWLINK to locate the VC redist. When VS shipped it's latest update (3.5), the FWLINK was updated so on clean installs the CLI will fail because it's expecting an older copy of the VC redist and the file hash no longer matches.

The fix only addresses the file hash issue, the VC redist is still an external download that runs when installing on a machine without the redist

**Comment by muratg** [comment]
Closing as "external".

**Comment by GuardRex** [comment]
@joeloff I have two error exceptions in the log now for when the VC++ isn't installed.

My testing shows 0x80072efd ... but @comburo shows 0x80072f76 in this issue.

Should I list them both in the common errors entry of Pub IIS?

**Comment by IonRobu** [comment]
I have Windows Server 2012 x64 (no R2, no SP), i tried to install Windows Server Hosting 1.0.5&1.1.2, but i received "Error 0x80072ee7: Process returned error: 0x2ee7". I have installed vc_redist.exe already, being administrator on that machine. It seems to install AspNetCoreModule, but not runtime. Any ideas?

**Comment by joeloff** [comment]
@IonRobu The runtime install in the bundle will attempt to detect the VC redist. There was an issue with a VC redist release around the time of VS2015 Update 3 RC where the registry keys it wrote were absent, causing the runtime to think that vc_redist wasn't present and then attempting to install an older version of it. That is most likely the reason for the failure.

Two asks
1. There should be a log from the vc_redist that the runtime tried to install in your %temp% folder. Could you maybe attach that.
2. Can you confirm what the version of the vc_redist is that you have installed? You should be able to find it in ARP (From the start menu, just launch appwiz.cpl to open the Programs & Features console)

**Comment by IonRobu** [comment]
@joeloff You're right, i pre-installed vc_redist 14.0.23026, but runtime 1.0.5-1.1.2 requires 14.0.24215 version. Because was not there, it tried to download it during install -> i have no internet on that machine -> setup failed. Questions: 1. is it possible to embed vc_redist in runtime setup? or 2. is it possible to display explicit error messages when setup fails?

Thanks!

**Comment by joeloff** [comment]
@IonRobu In 2.0.0 we've removed the vc redist dependency, but for 1.0.0 there's unfortunately not much we can do unless we ship a rebuild (that's very unlikely). The big problem with surfacing a decent error message is that it's coming from a nested bundle (the redist is nested into the runtime which in turn is nested into the server host).

The error you received is from the runtime trying to go online to download the redist. You're only recourse would be to download a copy of the redist and install that prior to running the server host.

However I will bring this up with the runtime owners in case there is another 1.x release. The other option would be to include the redist in the server host and simply install it before the runtime. I'll open an issue for the hosting bundle so that we can include the redist if we ship another 1.x release.

**Comment by IonRobu** [comment]
Oh, but this is enough, to eliminate vc_redist dependency! It's a good thing! So, this effort, to solve the problem in 1.x, probably has no sense, since 2.0 is knocking on the door.

**Comment by DipeshMitthalal** [comment]
I am still facing the problem when i try to install ANCM 2.0 bundle on Winserver 2016 which has ANCM 1.1.0 installed.
