### ISSUE TITLE
The specified framework 'Microsoft.NETCore.App', version '1.1.2' was not found.

### ISSUE THREAD

**Issue by DeveloperUniversity** [aspnet/IISIntegration#368]
After 6 weeks of successful continuous deployments to Azure WebApp (Websites), now I can't get anything to work.  I was getting IIS 502.5 errors and found that it was probably a version incompatibility.  Based on the advice in several threads, I added a web.config and turned on stdout logging and got this:

` The specified framework 'Microsoft.NETCore.App', version '1.1.2' was not found.`
`  - Check application dependencies and target a framework version installed at:`
`      D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App`
`  - The following versions are installed:`
`      1.0.0`
`      1.0.0-rc2-3002702`
`      1.0.1`
`      1.0.3`
`      1.0.4`
`      1.1.0`
`      1.1.0-preview1-001100-00`
`      1.1.1`
`  - Alternatively, install the framework version '1.1.2'.`

Lovely.  I guess I updated to 1.1.2 inadvertently.

Any ideas on how to remedy this?  Thank you!

**Comment by wags** [comment]
In your `.csproj` file, are you targeting a specific version in `TargetFramework` and `RuntimeFrameworkVersion`? Also, have your package reference versions been bumped up to `1.1.2`?

You should be able to keep it at 1.1.1 with `<TargetFramework>netcoreapp1.1</TargetFramework>` and `<RuntimeFrameworkVersion>1.1.1</RuntimeFrameworkVersion>`.

**Comment by DeveloperUniversity** [comment]
@wags 

@wags 
@wags In my csproj I have the following:

`
  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>
`

However, I do not have a `<RuntimeFrameworkVersion>` at all.  Is that what I need to do?
Thank you!!!

**Comment by muratg** [comment]
@DeveloperUniversity Yes, you'll need to do that too. Azure App Service doesn't yet have 1.1.2, and once they have it, this workaround will not be required.

**Comment by wags** [comment]
@muratg can it be problematic if the `Microsoft.AspNetCore.X` and `Microsoft.Extensions.X` packages get ahead of the runtime version? I'm assuming no if it is a minor version difference but wanted to double-check.

**Comment by muratg** [comment]
@wags In this case, it's not even a minor version difference, just a patch version difference. Wouldn't be a problem.  We roll ASP.NET Core packages without a runtime patch at times.

**Comment by DeveloperUniversity** [comment]
@muratg @wags Two final questions ...

1) Where can I go to learn more about versioning in .Net Core and specifically with ASP.NET MVC Core, how @wags knew to go to the csproj, etc.?  I want to be able to diagnose things like this in the future and I think I'm missing some important piece of knowledge here.

2) Any experience on how long it typically takes for the Azure Web Apps (Websites) team to get the latest version of the assemblies installed and available?

Thank you both very much for your very fast and very kind responses.

**Comment by j-arya** [comment]
FYI:
I encountered the similar error due to Microsoft.NETCore.App getting upgraded to 1.1.2 (upgraded while updating NuGet packages); 
As part of work around, rolling back to "Microsoft.NETCore.App": { "version": "1.1.1"} in Project.json does help fix the issue

My Environment Details:
- VS2015 Community Edition
- Asp.Net Core Web App
- Running on Windows 10

Note:
- Work around Not applicable if using VS2017/.csproj file for package management
- My application was NOT Hosted live i.e. was running in Debug mode via VS when i encountered the same issue

Please refer the attached file named "502_5ServerError.png" screenshot to view the issue
![502_5servererror](https://cloud.githubusercontent.com/assets/27440077/25974206/76fd47ec-36b0-11e7-842e-1c1af8c2dbdc.png)

**Comment by wags** [comment]
@DeveloperUniversity for me, it has been an iterative process. The .NET Core project development is definitely moving fast, and changing. For example, I had familiarity with the `.csproj` file because it was involved in a fairly significant change to .NET Core tooling. Earlier versions of .NET Core used a file called `project.json` to keep track of dependencies, versions, targets, etc. 

I end up reading [the docs](https://docs.microsoft.com/en-us/aspnet/core/) a lot and I try to keep tabs on what other people are doing via blog posts, tutorials, and sometimes online training. Like working with any framework/library, the best way to learn it is to roll up your sleeves and dig right it. It can be painful, but the topics usually stick and make more sense when you've lived it. I love that we can keep tabs on the project right here on GitHub. Jump on the [.NET Core Slack channel](https://aspnetcore.slack.com/) too (sign up [here](http://tattoocoder.com/aspnet-slack-sign-up/)). I've learned some interesting things there and have connected with people who have helped me resolve some real head-scratchers.

Can't really speak to your second question since I haven't done enough deployment to Azure to note their release patterns or schedule.

**Comment by Roblinde** [comment]
@muratg any timeline on when Azure App Service will have 1.1.2? Running into the same issue.

**Comment by DeveloperUniversity** [comment]
Also, *if* I wanted to roll back to 1.1.1, would I simply need to change the csproj -- everywhere there's a 1.1.2 change it to 1.1.1?

![1-1-2-rollback](https://cloud.githubusercontent.com/assets/19307883/26008447/6f618ac0-370a-11e7-9fd7-45f562364c33.png)

**Comment by wags** [comment]
> Also, if I wanted to roll back to 1.1.1, would I simply need to change the csproj -- everywhere there's a 1.1.2 change it to 1.1.1?

Yes, that's correct. You also have `Microsoft.AspNetCore.Mvc` in there at version `1.1.3`. That's an example of how the various patch versions are still compatible, like @muratg mentioned.

BTW, I love your project name :wink:

**Comment by muratg** [comment]
@Roblinde I believe the Azure rollout of the patch is scheduled for next week, though I don't have the exact dates.  @davidebbo?

**Comment by Roblinde** [comment]
Next week is excellent!

Is it expected for Azure to lag on official releases like this? It makes it sort of dangerous to deploy if it's going to respond with a 502 after every minor release...

**Comment by davidebbo** [comment]
It's already partially deployed (e.g. try in West US 2). It will complete Tuesday at the latest, but hopefully sooner.

And we'll work to avoid/minimize this situation in the future :)

**Comment by davidebbo** [comment]
See also http://stackoverflow.com/a/43924403/111888

**Comment by Roblinde** [comment]
Great @davidebbo thank you.

**Comment by davidebbo** [comment]
We have accelerated the deployment of 1.1.2 and 1.0.5 to App Service and it is now complete. So the workaround below should no longer be needed by anyone.

Apologies for the inconvenience this has caused.

@muratg, can you close?

**Comment by muratg** [comment]
Thanks @davidebbo! Closing this bug, but if folks hit other issues, they should log another one.

**Comment by rsheptolut** [comment]
@davidebbo I wouldn't agree that the workaround is no longer needed by **anyone**. 

Not every app is deployed to Azure. I haven't used Azure once in my life :) I had the same issue today just because I've updated Visual Studio 2017 to version "15.2". After publishing the same unchanged app (that only has `<TargetFramework>netcoreapp1.1</TargetFramework>` but no `<RuntimeFrameworkVersion>` to a remote server which only has NETCore 1.1.1 installed, the production app broke, asking for 1.1.2. And I preferred to fix this by the workaround which @wags provided (much thanks!), because updating a framework on a production server requires admins, caution, some time, etc.. Also it's a very bad thing that the app broke by itself, just because I've updated Visual Studio, and this workaround mitigates/prevents this. I actually think that there still is a bug somewhere: if I only have netcoreapp1.1 specified and my server only has 1.1.1 it should not, under any circumstances, fail because it wants 1.1.2 for some reason. I'm not that familiar with the new NETCore toolset, so I don't completely understand which component is to blame here.

**Comment by muratg** [comment]
@rsheptolut We have some plans in place to prevent this type of failure going forward, at least in the 2.x train.  @livarcocc would have more information.

**Comment by livarcocc** [comment]
Correct. We actually have a PR out right now for 2.0 and if/when we need to do this again in 1.0, we will port the fix there as well.

**Comment by grokky1** [comment]
I agree with @rsheptolut about always specifying a `<RuntimeFrameworkVersion>`. And I think it's bad practice not to use it.

When our systems go to production, they are completely tested and signed-off *for a specific version of everything*. We don't "pull latest sources" for .NET or npm packages and runtimes, or whatever, we hardcode the versions of all packages used by the system - because then that release is KNOWN TO WORK.

When you rely on implicit versions, for example by not using `<RuntimeFrameworkVersion>` then you get the problems others have mentioned above. So you need to choose versions explicitly, not implicitly.

When a new version of something is released, don't just "pull latest". You need to test that it works with what you have first. If it does, then manually update all versions. Then redeploy.

Only exception I guess, is if you are working on a "small" system, or maybe your team is small. Then you can cut corners with less risk.

**Comment by jcmrva** [comment]
I encountered this issue today - adding <RuntimeFrameworkVersion>1.1.1</RuntimeFrameworkVersion> to *.csproj took care of it.

Not sure which link I followed to get the file originally, but DotNetCore.1.0.4_1.1.1-WindowsHosting.exe is still floating around.

**Comment by VictorioBerra** [comment]
It sounds to me like if `<RuntimeFrameworkVersion>` is missing (which when creating a new project with the latest dotnet CLR it **is**) then it will automatically target 1.1.2 which is crazy to me, why is it like this?

## I was able to fix mine by adding:

```
<RuntimeFrameworkVersion>2.0</RuntimeFrameworkVersion>
```

**Comment by softsan** [comment]
I've updated VS 2017 to 15.4.4 Yesterday and then one of my app targeting to 1.1 was not working anymore. I tried adding `<RuntimeFrameworkVersion>1.1.1</RuntimeFrameworkVersion>`
but it didn't help much.

So I went back to VS installer and found that VS has installed .net core 2.0 and put 1.1 in optional category. So i have to re-install that version.

<img width="1245" alt="vs-update" src="https://user-images.githubusercontent.com/7391319/33273244-b4900820-d3b2-11e7-92cd-57515cc65b72.png">

Hope this helps someone who face problem similar to me.

**Comment by ianrathbone** [comment]
@softsan thanks this helped me!

**Comment by SamShekhovtsov** [comment]
guys, this thing is completely crazy. Visual Studio updater is removing the current dotnet framewrok version. Are we sick? where the world is going to.

**Comment by muratg** [comment]
@softsan @ianrathbone @SamShekhovtsov the VS issue is not directly related to the issue discussed here, though. Could you guys give the feedback through VS feedback tool?

**Comment by 68681395** [comment]
There is the same problem with my project, the workaround to resolve it successfully is that remove the item 'C:\Program Files (x86)\dotnet' from the Path of Environment Variable because I found I did not install the right netcore version under X86.  I have not tried to install the proper version with x86,  appreciate that you tell me if you have done that test.

**Comment by Seakone** [comment]
Happened to me and solved adding this line as @wags troubleshooting. Dunno but this line missed in my *.csproj.  

<RuntimeFrameworkVersion>1.1.1</RuntimeFrameworkVersion>.

**Comment by Smile4ever** [comment]
I fixed it by installing DotNetCore.1.0.5_1.1.2-WindowsHosting:
https://go.microsoft.com/fwlink/?linkid=848766

Source https://stackoverflow.com/questions/47349608/how-to-fix-microsoft-netcore-app-version-1-1-2-was-not-found
