### ISSUE TITLE
How do we fall through IIS when using IISPlatformHandler? 

### ISSUE THREAD

**Issue by Tratcher** [aspnet/IISIntegration#40]
_From @dealdiane on November 20, 2015 10:12_

Now that ASPNET 5 runs on kestrel only how do we fall through IIS? There used to be an `app.RunIISPipeline()` but I couldn't find this anywhere anymore.

I hope this was not forgotten. https://github.com/aspnet/Hosting/issues/323

_Copied from original issue: aspnet/Hosting#491_

**Comment by Tratcher** [comment]
_From @davidfowl on November 20, 2015 14:28_

You don't fall through IIS anymore. It's a reverse proxy

**Comment by Tratcher** [comment]
_From @dealdiane on November 20, 2015 17:16_

Yes, that's what I thought actually. I've tried serving static files through IISExpress and expected it to just work without adding `app.UseStaticFiles` but it doesn't seem to just work. If I remove the IISPlatformHandler module, static files work (with compression which what I've configured).

How do we take advantage of IIS's feature like static compression and etc? They don't seem to work (at least static files no longer work without adding `app.UseStaticFiles`?

**Comment by muratg** [comment]
Let's test this to see the behavior and either document it or change it.

**Comment by GuardRex** [comment]
@Tratcher If you're busy and need a worker bee, I'm happy to help. but btw --- IIS static and dynamic compression are working in IIS 8/8.5 AFAIK according to my testing. I can take another look if you like.

**Comment by dealdiane** [comment]
@GuardRex I'm interested on how you got it working.

What I've tried so far is:

1. Create a new web project in Visual Studio using the "Empty" template
2. Add a static file in /www.
3. Publish and setup an IIS website
4. Try access the static file from a browser - This bit doesn't work even if you explicitly set the static file handler before or after the `HttpPlatformHandler`. If you uncomment `HttpPlatformHandler`, IIS will load the static file (with compression if set).

**Comment by GuardRex** [comment]
@dealdiane Good morning ... a few quick, simple things ...

When you typed "/www," you meant "/wwwroot," right?
You have the `"Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",` package in place, correct?
The application is responding normally otherwise, correct? I mean is it returning MVC views normally?

As for the order of the statements (or even the presence of `app.UseIISPlatformHandler();`), it doesn't matter in this case. The order doesn't matter; and in my testing, `app.UseStaticFiles();` is all that is required and I didn't even need to have `app.UseIISPlatformHandler();` to get static files returned. However, in practice I always go with ...
```
app.UseIISPlatformHandler();
app.UseStaticFiles();
```
If static files still won't serve, can you put up a Github repo? I'll run it here and see if I can get it working. I suspect you have a more general issue with the app and/or the IIS config than the statements.

**Comment by dealdiane** [comment]
@GuardRex Yes, sorry I mean /wwwroot. You see, I purposely left out installing `Microsoft.AspNet.StaticFiles` because I didn't want Kestrel to serve the static files for me. I wanted IIS to take care of it and use its built-in features (specifically static compression here) and you're right if I add in `Microsoft.AspNet.StaticFiles` and `app.UseStaticFiles`, all my static files get returned but without compression but this isn't the goal here.

**Comment by GuardRex** [comment]
@dealdiane It should be working on reverse proxyed content. This is with Kestrel and the static files package. Here's a Fiddler shot showing that I'm asking for gzip compression and getting a gzipped response of a `robots.txt` file. The response header for the `Content-Encoding` is being added there by IIS on the way out.

![capture](https://cloud.githubusercontent.com/assets/1622880/11609349/5cb582fa-9b39-11e5-9789-e40ca2ed7dac.PNG)

I suggest setting up your app with the Kestrel and static files bits, deploy, then try the same thing and see if you get a similar response out of IIS when you specifically make the request with an `Accept-Encoding: gzip` header. Now, if that doesn't work, then yeah ... something in the IIS compression isn't working.

**Comment by GuardRex** [comment]
@dealdiane ... and forgive me if you already did all of that. I re-read your post, and it seems perhaps you may have confirmed it wasn't working. If that's the case, I'd look more carefully at the IIS-side of things. I'm sure you set IIS static compression, too, in the IIS Manager. If it's all configured correctly and still broken, then I'm sort of out out ideas. Except if you do put up a repo, I would be happy to run it on one of my staging VM's to see if it works here.

**Comment by Tratcher** [comment]
IIS's dynamic compression works with reverse proxied content, but it's static compression doesn't.

I think one way to make IIS handle static files by default is to update this line of the web.config
`<add name="httpplatformhandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified" />` so that not all paths or verbs are forwarded to Kestrel. This may be easier said than done.

**Comment by GuardRex** [comment]
Ah, yes, I see.

![capture](https://cloud.githubusercontent.com/assets/1622880/11609674/14f7dfe0-9b42-11e5-9f9f-4be0cf0d1e39.PNG)

![capture2](https://cloud.githubusercontent.com/assets/1622880/11609679/5c0a75fa-9b42-11e5-8501-428b6a022581.PNG)

... and maybe something inside the Handler Mappings along those lines ...

![capture3](https://cloud.githubusercontent.com/assets/1622880/11609703/eeec4ccc-9b42-11e5-9629-8995dabd3b6d.PNG)

**Comment by Tratcher** [comment]
Note: this can only be achieved with IIS handler mappings.
