### ISSUE TITLE
Unable to publish to Azure with HTTP Error 502.5 - Process Failure

### ISSUE THREAD

**Issue by haydenhancock** [aspnet/IISIntegration#681]
I am having issues deploying to Azure, even though the publish "succeeded." [This](https://github.com/haydenhancock/WebApplication4) repository can be used as an example. ~~I've had similar issues on multiple version of Visual Studio 2017 (include 15.6.2 and 15.5.2) using the default ASP.NET Core templates.~~

The issue only seems to be related to the latest version of Visual Studio 2017, which is 15.6.2 using the default ASP.NET Core templates. Specifically, using the NuGet package Microsoft.AspNetCore.All (2.0.6). In addition, downloads to previous versions of Microsoft.AspNetCore.All cause the build to fail.

#406 is similar to my issue but I was told to open a new one to include a repository.

**Comment by davidebbo** [comment]
Is this a scenario where you are git pushing to Azure (i.e. build on Azure), or you are deploying from VS via WebDeploy (i.e. build locally)?

Also, when you say "cause the build to fail", can you provide to complete error that you are getting?

**Comment by davidebbo** [comment]
I just tried git pushing this repo to a clean new Azure Web App, and everything works fine. It builds without errors, and I can then access `/api/values` in the running app.

**Comment by haydenhancock** [comment]
@davidebbo I am deploying directly through Visual Studio using the Publish menu.

This repository was built and published with the older version of Visual Studio (15.5.2) that seems to work fine (which is why I put a line through the "multiple versions of Visual Studio" sentence).

This issue could be related to Microsoft.AspNetCore.All (2.0.6) not being available on Azure until today. I will upgrade my version of Visual Studio to the latest and try again.

**Comment by davidebbo** [comment]
I'll let core experts like @Tratcher comment on some of this. My expectation is that the build artifact produced by VS cannot be influenced by the version of Core that happens to be on Azure. Instead, it will produce whatever artifacts it thinks are right for the project, and will deploy that. Then how that **runs** on Azure can depend on what's available.

**Comment by haydenhancock** [comment]
Updated Visual Studio 2017 to 15.6.2; created a new API project using ASP.NET Core Web Application and published to Azure without issue. In addition, I attempted to downgrade Microsoft.AspNetCore.All to 2.0.5 and rebuilt without issue.

I am going to run a repair on my other installation of Visual Studio and see if that resolves the issues I was seeing yesterday. I am closing this issue.

Thanks for your help!

**Comment by henrychang99** [comment]
Hello - I am encountering this issue with VS2017 15.7.1 Enterprise.  I have created a .net core 2.0 mvc project.  made some cosmetic changes to it and published to azure.  the publish was successful but got 502.5 error. 

i have tried the wwwroot wipe and not successful.

in the log, i got this
8000808c.100010Keywords1129163281ApplicationRD00155DFE9F35Application 'MACHINE/WEBROOT/APPHOST/DEVARCOSACOM' with physical root 'D:\home\site\wwwroot\' failed to start process with commandline 'dotnet .\xyz.com.dll', ErrorCode = '0x80004005 : 8000808c.100420Keywords1129293625ApplicationRD00155DFE9F35Warning: Could not create stdoutLogFile \\?\D:\home\site\wwwroot\logs\stdout_8344_201851116448.log, ErrorCode = -2147024893.100010Keywords1129293921ApplicationRD00155DFE9F35Application 'MACHINE/WEBROOT/APPHOST/DEVARCOSACOM' with physical root 'D:\home\site\wwwroot\' failed to start process with commandline 'dotnet .\xyz.com.dll', ErrorCode = '0x80004005 : 8000808c.

Is there any other information i can post there so that we can have better idea?

Thank you,
Henry

**Comment by asciimos** [comment]
I experienced that too.. **Azure with HTTP Error 502.5 - Process Failure** 

In my case, I resolved the problem by updating my .net core sdk to the latest **2.1 SDK (v2.1.302)**.

**Comment by DanJ210** [comment]
It looks like the issue is that the VS 2017 templates use the latest updated NuGet packages which is right, it's good. But Azure isn't prepared for these so Azure will not run the latest. I had to downgrade packages to a lower version to where the App then did run. This wasn't a framework downgrade, this was NuGet package minor version downgrades.

**Comment by ru-sh** [comment]
You can configure the publish profile in VS2017 to use Self-Contained mode.
It will publish all dependencies, so you will be able to run your web app in Azure.

Make sure the target runtime corresponds to the configuration of web app in Azure.

**Comment by DanJ210** [comment]
@ru-sh for new people creating new templates and publishing those apps like directed from VS 2017, those are extra steps that might not be obvious. I can try them the next time I play around and run into the above issues but hopefully Azure is now prepared for the latest packages. At least by now.

**Comment by James-Jackson-South** [comment]
It's not ready; I had to publish as a self contained app last night, took me hours to figure it out also.

Incredibly frustrating.

**Comment by DanJ210** [comment]
@James-Jackson-South I still need to remember to try this. Why wouldn't self-contained mode be on by default I wonder? Or at least could it be explained in the process that 2017 provides us.

**Comment by estomagordo** [comment]
Thank you @ru-sh - self-contained did the trick.

**Comment by aqanonas** [comment]
> 
> 
> I experienced that too.. **Azure with HTTP Error 502.5 - Process Failure**
> 
> In my case, I resolved the problem by updating my .net core sdk to the latest **2.1 SDK (v2.1.302)**.

Same issue with me, updating the .net core sdk also resolved my issue. Thanks!
