### ISSUE TITLE
ANCM slow perf - 2 times worst than net461 ?

### ISSUE THREAD

**Issue by rducom** [aspnet/IISIntegration#747]
Just tried some very minimal project to evaluate aspnet core 2 perf. With a really minimal controller returning json : 

```
    [Route("api/[controller]")]
    public class ValuesController : Controller
    {
        // GET api/values
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }
    }
```

Tested on a i7-6700HQ with wrk on localhost

Net461 on IIS : 10 000 r/s and 40ms latency :

![image](https://user-images.githubusercontent.com/5228175/38165276-5501c572-3511-11e8-8b53-b36d5ed1e5e3.png)

NetCore2 on kestrel : 33 300 r/s and 12ms latency : 

![image](https://user-images.githubusercontent.com/5228175/38165289-7af25724-3511-11e8-816b-bbc377057117.png)

NetCore2 on kestrel+IIS with ANCM : 4700 r/s and 83ms latency : 

![image](https://user-images.githubusercontent.com/5228175/38165300-a9382a5a-3511-11e8-8b65-e6cb35ba67fb.png)

So using aspnet core 2 on IIS is **2 times slower** than legacy Net461.

All test apps are published in release mode. Aspnet core one using the win10-x64 RID. 
All IIS modules are removed from the aspnet core IIS test, except "anonymous auth" and ANCM. (as stated here https://github.com/aspnet/Performance/issues/186)
Windows defender is disabled.
All test are saturating the CPU.

Interestingly, IIS with ANCM seems to be the bigger CPU consumer (perfcore.exe is the aspnet core test project)
![image](https://user-images.githubusercontent.com/5228175/38165536-29fea742-3515-11e8-9237-52cc27af66c8.png)

Maybe related : https://github.com/aspnet/IISIntegration/issues/587

**Comment by bangbingsyb** [comment]
Question: the test was for ANCM in-proc or out-of-proc mode?

There is a big problem of the minimum module configuration used in the test, and only including AnonymousAuthenticationModule and the ANCM will make the performance much worse than the default applicationHost.config in a synthetic benchmark using a very simple app.

The reason is the missing of UriCacheModule in this configuration. UriCacheModule doesn't have any configuration you can set, so people often forget its existence. However, it actually helps IIS caches merged configuration at URL level (it is not a response cache, otherwise enabling it in the perf test might sound cheating). Without this module, IIS has to read and parse configuration for every request, even if they might target to the same URL, and the configuration reading cost is significant in comparison with the rest of request processing for helloworld-style test.

**Comment by rducom** [comment]
It's with asp.net core 2.0 so outt of proc (as far as I know, only asp.net core 2.1.0-preview1 has the in-proc setting). I have made these test With and Without all the other modules. 
With the minimal modules : 5034 r/s
With all modules : 4758 r/s (the provided screenshot)

So only leaving the 2 mentioned modules give a little gain, and doesn't make perf worse.

**Comment by rducom** [comment]
After checking the modules, I didn't find any "UriCacheModule" in my IIS 10 modules....

**Comment by rducom** [comment]
Ok, so this module is not present by default. (this should really be documented, or better, installed automatically with ANCM).
I have had to add it via the IIS root -> modules -> configure native modules.

After adding this module, removing all the others except "anonymous auth" and ANCM, I've done another benchmark : 

Here are the results : 
![image](https://user-images.githubusercontent.com/5228175/38166207-3719224e-3520-11e8-8a0d-fd7123bb17a8.png)

That's maybe 10% better, but it's still **40% less than net461**...

**Comment by bangbingsyb** [comment]
I would say it is expected that the out-of-proc mode of  kestrel+IIS with ANCM is slower than Net461 on IIS due to the fundamental architecture difference. For the our-of-proc mode,  IIS + ANCM essentially form a reverse proxy for the app server, and the communication between the two parties goes through the entire network stack four times even they are both on the same machine. For example, ANCM uses winhttp to send/receive -  going through the entire network stack twice, and kestrel has a similar scale cost for sending/receiving. On the other hand, Net461 on IIS  doesn't pay this cost.

I think performance is the major motivation for the new in-proc mode, and believe eventually the in-proc mode would become faster or at least comparable to Net461 on IIS.

**Comment by bangbingsyb** [comment]
BTW: because of dominant overhead of extra round-trips through network stacks, adding UriCacheModule in your our-of-proc test only boosts the perf for about 10%.

In our initial perf test for in-proc mode: https://github.com/aspnet/benchmarks/pull/428#issuecomment-376364339

The minimal configuration without UriCacheModule gives almost half of the throughput with respective to the test with the default applicationHost.config with that module. And adding UriCacheModule to the minimal configuration gives a throughput gain about 8% with respect to the default  applicationHost.config.

**Comment by bangbingsyb** [comment]
I also checked the default IIS installation on Win10 -  by just selecting and enabling "Internet Information Services" without further expanding the features. Here is the default global module list and it does include UriCacheModule:

        <globalModules>
            <add name="HttpLoggingModule" image="%windir%\System32\inetsrv\loghttp.dll" />
            <add name="UriCacheModule" image="%windir%\System32\inetsrv\cachuri.dll" />
            <add name="FileCacheModule" image="%windir%\System32\inetsrv\cachfile.dll" />
            <add name="TokenCacheModule" image="%windir%\System32\inetsrv\cachtokn.dll" />
            <add name="HttpCacheModule" image="%windir%\System32\inetsrv\cachhttp.dll" />
            <add name="StaticCompressionModule" image="%windir%\System32\inetsrv\compstat.dll" />
            <add name="DefaultDocumentModule" image="%windir%\System32\inetsrv\defdoc.dll" />
            <add name="DirectoryListingModule" image="%windir%\System32\inetsrv\dirlist.dll" />
            <add name="ProtocolSupportModule" image="%windir%\System32\inetsrv\protsup.dll" />
            <add name="StaticFileModule" image="%windir%\System32\inetsrv\static.dll" />
            <add name="AnonymousAuthenticationModule" image="%windir%\System32\inetsrv\authanon.dll" />
            <add name="RequestFilteringModule" image="%windir%\System32\inetsrv\modrqflt.dll" />
            <add name="CustomErrorModule" image="%windir%\System32\inetsrv\custerr.dll" />
        </globalModules>

**Comment by rducom** [comment]
About this module, it was installed, yes, but not present by default in the active ISS modules. Have had to add it. Maybe a pb on my side, but I doubt, since native modules are locked by default, and I didn't unlocked any module until today to delete it. So....

About the inprocess mode, and the IIS performances lower than net462 atm, I think I don't get the point for windows hosts : 

How are we supposed to deploy in production in order to enjoy the kestrel performance added value ?
Are we supposed to install our kestrel app as windows service behind haproxy ? Are we supposed to dockerize it ? 

Really confused...

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
