### ISSUE TITLE
Microsoft ASP.NET CoreModule for IIS Express(V1) disappeared in ARP during the installation of VS but related files are not gone

### ISSUE THREAD

**Issue by Jinjin2Ma** [aspnet/IISIntegration#827]
Description:  Microsoft ASP.NET CoreModule for IIS Express(V1) disappeared in ARP during the installation of VS but related files are not gone.
Repro steps:
1.Install  V1 version for both IIS/IISExpress
2.Install V2 for both IIS/IISExpress
3.Install VS2017 
Expected:The ANCM for IIS Express(V1) in ARP shows as normal.
Actually: The ANCM for IIS Express(V1) disappeared in ARP during install VS2017

**Comment by Tratcher** [comment]
It's considered a bundled component of VS/WTE, correct?

**Comment by jhkimnew** [comment]
@Jinjin2Ma. When ANCM is installed as a bundled component, we should not show in ARP, which is by design. Please check if the expected files are still remained. The expected files are higher version comparing between the standalone V1 and the ANCM bundled in VS. After verifying that, please test one more thing. When VS is uninstalled, the ANCM should be uninstalled together.
